version: '3'

services:
    rundeck1:
        hostname: rundeck1
        image: ${RUNDECK_IMAGE:-rundeck/rundeck:SNAPSHOT}
        links:
          - ldap
        tty: true
        environment:
version: '3'

services:
    rundeck1:
        hostname: rundeck1
        image: ${RUNDECK_IMAGE:-rundeck/rundeck:4.7.0-rc3-20221003}
        tty: true
        environment:
        ### Active directory configurations
        #AD ESPECIFICY CONFIGURATIONS
          #ROLES
          RUNDECK_JAAS_LDAP_ROLEBASEDN: OU=permissoes,OU=perfis,OU=test,DC=com
          RUNDECK_JAAS_LDAP_ROLEMEMBERATTRIBUTE: "member"
          RUNDECK_JAAS_LDAP_ROLEOBJECTCLASS: "group"
          RUNDECK_JAAS_LDAP_ROLENAMEATTRIBUTE: "cn"
          RUNDECK_JAAS_LDAP_SUPPLEMENTALROLES: "user,readonly"
          #USERS
          RUNDECK_JAAS_LDAP_USERBASEDN: OU=usuarios,OU=contas,OU=tesst,DC=com
          RUNDECK_JAAS_LDAP_USERRDNATTRIBUTE: "sAMAccountName"
          RUNDECK_JAAS_LDAP_USERIDATTRIBUTE: "sAMAccountName"
          RUNDECK_JAAS_LDAP_USERPASSWORDATTRIBUTE: "unicodePwd"
          #CONFIGS CONNECTION
          RUNDECK_JAAS_LDAP_CACHEDURATIONMILLIS: "300000"
          RUNDECK_JAAS_LDAP_REPORTSTATISTICS: "true"


          RUNDECK_JAAS_MODULES_0: JettyCombinedLdapLoginModule
          RUNDECK_JAAS_LDAP_PROVIDERURL: ldap://192.168.0.1:389
          RUNDECK_JAAS_LDAP_BINDDN: s_rundeck,OU=servicos,OU=contas,OU=test,DC=com 
          RUNDECK_JAAS_LDAP_BINDPASSWORD: "<STRONG_PASSWORD>"
          RUNDECK_SECURITY_HTTPHEADERS_ENABLED: "0"
          RUNDECK_JAAS_MODULES_1: PropertyFileLoginModule
          RUNDECK_JAAS_FILE_FLAG: sufficient
          RUNDECK_JAAS_LDAP_FLAG: sufficient
        ports:
          - 4440:4440
        volumes:
          - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
        ports:
          - 4440:4440
    ldap:
        hostname: ldap
        image: osixia/openldap:1.2.1 
        environment:
          - LDAP_ORGANISATION=RD Test
          - LDAP_DOMAIN=rdtest.com
          - LDAP_ADMIN_PASSWORD=AdminPass123
        volumes:
          - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom:rw
        ports:
          - "389:389"
        command: --copy-service
